### ISSUE TITLE
Finalize release pipeline

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#361]
Move to github actions:
- [x] 1.Add external actions for markdown linting (on push) and link checking (on pr)
- [x] 2.Add composition of documents to github action
   - [x] github and gitbook rendering: fix logo/image width rendering: have img tags everywhere and a replacement/conversion script just before rendering documents.
   - [x] PDF
      - [x] Fix markdown errors 
      - [x] Fix header and footer
      - [x] check all PDFs and add pagebreaks where needed (e.g. only head on the page: wip https://github.com/OWASP/owasp-masvs/pull/383)
     ```html
     <div style="page-break-after: always; visibility: hidden">
     \pagebreak
     </div>
      ```
   - [x] Word
      - [x] Fix reference doc for better layouting
      - [x] Add cover (Separate docx and then do https://stackoverflow.com/questions/24872527/combine-word-document-using-python-docx )
      - [x] Add missing docx uploads
   - [x] Epub
      - [x]  ~Have customized cover.jpg per language to show the language~
      - [x] Add more metadata: authors, and language
      - [x] Have basic generation of epub
      - [x] Upload all epubs
   - [x] Mobi
   - [x] python xml/etc. generator
- [x] 2-B: update templating with new creation tools (template added to tools for editting)
  - [x] PDF
  - [x] Word
  - [x] Epub
  - [x] Mobi
- [x] 3.Add releasing on tags (https://github.com/marketplace/actions/automatic-releases ? ) - see #383
- [x] FIX 2 byte languages spacing for PDF (Korean, Chinese, etc.)
- [x] 4.Create release
- [x] Github/gitbook: fix the rendering of the git and gitbook of pagebreaks,similar like hte image rewrite.
- [ ] 5.Migrate release actions (e..g 1 (todo)&2 (#404))to external container on docker hub (wiht a github action?) and create actions as well as supporting scripts to use the containers locally
- [ ] 6.Add instructions on architecture/readme in tools and in readme section
- [x] 7.Testdrive release till it works
- [ ] 8. Decom old material
     - [x] - Get rid of all scripts that aren't required anymore to keep the repo clean and simplify tools and docker folder.
     - [ ] - Remove images that have been copied for no good reason.

- [ ] Fix Persian translation issues #399  
- [ ] Fix Hindi translation issues #415

**Comment by commjoen** [comment]
Question: do we really want different epub cover images per language? otherwise epub and mobi are done 👍

**Comment by commjoen** [comment]
Question 2: can we skip docx reference document markup stuff for now? and move to the releases?

**Comment by commjoen** [comment]
if we want to fix the rendering of images then we need a script that converts the IMG HTML tags to IMG Markdown tags before rendering the stuff, then all will be fine

**Comment by commjoen** [comment]
https://owasp.slack.com/archives/C04T40NND/p1583686780213100?thread_ts=1583612028.204600&cid=C04T40NND

**Comment by TheDauntless** [comment]
Updated branch to have linebreaks. In markdown, we use the HTML to hide it, and during the build process they are swapped with the content of the HTML comments.

**Comment by cpholguera** [comment]
all addressed in #503
